### ISSUE TITLE
Add FileAlredyExist exception on file upload

### ISSUE THREAD

**Issue by avgar** [wix/media-platform-java-sdk#5]
current exception is general: IOException

**Comment by golanpa** [comment]
@avgar Please add more information on this. Which SDK call throws the error and what is the reason (already existing file?)

**Comment by avgar** [comment]
regarding call:
public FileDescriptor[] **uploadFile**(String path, String mimeType, String fileName, File source, String acl) throws UnauthorizedException, IOException, URISyntaxException  

in 

public class **FileManager**

**Comment by alon-ne** [comment]
What's the error message in the exception, if any?

**Comment by avgar** [comment]
Exception: HttpResponseProxy{HTTP/1.1 406 Not Acceptable [X-GUploader-UploadID: AEnB2UqODr6I3EeP_5l9sa8fZFzlKBN01PIwwLrtmGzl0y5k4kZ4R1cabBOhpI7qa9k4totpfH6LwrVjDH8IGxkGJjl8BGuShw, Content-Type: application/json, Cache-Control: no-cache, must-revalidate, Access-Control-Allow-Origin: *, Access-Control-Allow-Methods: DELETE,GET,HEAD,POST,PUT, Access-Control-Max-Age: 21600, Access-Control-Allow-Credentials: true, X-Cloud-Trace-Context: fdd7c37338ac495e5bf6993cb2cfaa16, X-AppEngine-Estimated-CPM-US-Dollars: $0.000038, X-AppEngine-Resource-Usage: ms=353 cpu_ms=33, Vary: Accept-Encoding, Date: Tue, 04 Jul 2017 05:04:29 GMT, Pragma: no-cache, Expires: Fri, 01 Jan 1990 00:00:00 GMT, Warning: 214 UploadServer gunzipped, Content-Length: 59, Server: UploadServer, Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 59,Chunked: false]}}
	at com.wix.mediaplatform.http.AuthenticatedHTTPClient.post(AuthenticatedHTTPClient.java:97) ~[media-platform-java-sdk-5.2.0-20170702.054257-5.jar:na]
	at com.wix.mediaplatform.management.**## FileUploader**.uploadFile(FileUploader.java:68) ~[media-platform-java-sdk-5.2.0-20170702.054257-5.jar:na]
	at com.wix.mediaplatform.management.FileManager.uploadFile(FileManager.java:58) ~[media-platform-java-sdk-5.2.0-20170702.054257-5.jar:na]
	at com.wixpress.staticdeployservice.services.mediaplatform.MediaPlatformFacade$$anonfun$uploadFile$1.apply$mcV$sp(MediaPlatformFacade.scala:41) ~[static-deploy-server.jar:1.11.0-SNAPSHOT]
	at com.wixpress.staticdeployservice.services.mediaplatform.MediaPlatformFacade$$anonfun$uploadFile$1.apply(MediaPlatformFacade.scala:39) ~[static-deploy-server.jar:1.11.0-SNAPSHOT]
	at com.wixpress.staticdeployservice.services.mediaplatform.MediaPlatformFacade$$anonfun$uploadFile$1.apply(MediaPlatformFacade.scala:39) ~[static-deploy-server.jar:1.11.0-SNAPSHOT]

**Comment by alon-ne** [comment]
New exception added to SDK: com.wix.mediaplatform.exception.FileAlreadyExistsException

**Comment by Elad-Laufer** [comment]
done, thanks @alon-ne
